version: '3'
services:
  testing:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      DATABASE_USER: postgres
      DATABASE_PASS: 1234
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: findafriend